version: "3.8"

services:
  node1:
     build: .
     image: gravitas
     volumes:
             - ./node1:/bitcoin/node1:rw
     ports:
        - 18444:18444 
        - 18445:18445 
     command: bitcoind -regtest -datadir=node1 -debug=rpc -rpcport=18445

     



