version: "3.8"

services:
  node1:
     build: .
     image: gravitas
     volumes:
             - ./node1:/bitcoin/node1:rw
     ports:
        - 18444:18444 
        - 18443:18443 
     command: bitcoind -regtest -datadir=node1

     



