version: "3.8"

networks:
  minet:
     driver: bridge
     ipam:
        driver: default
        config:
         - subnet: 10.0.0.0/16
services:
  node1:
     user: ${CURRENT_UID}
     build: .
     image: gravity
     container_name: node1
     volumes:
             - ./node1:/bitcoin/node1:rw
     networks:
        minet:
           ipv4_address: 10.0.0.2
     command: bitcoind -regtest -datadir=node1

  node2:
     user: ${CURRENT_UID}
     image: gravity
     container_name: node2
     volumes:
             - ./node2:/bitcoin/node2:rw
     networks:
        minet:
           ipv4_address: 10.0.0.3
     command: bitcoind -regtest -datadir=node2

     

     



